# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: flatiron_mod3_development
  username: postgres
  password: admin

test:
  <<: *default
  database: flatiron_mod3_test
  username: postgres
  password: admin

production:
  <<: *default
  database: flatiron_mod3_production
  username: postgres
  password: admin
